/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as FalhasRouteImport } from './routes/falhas'
import { Route as ConfigAfiliadosRouteImport } from './routes/config-afiliados'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstagramTemplatesRouteImport } from './routes/instagram.templates'
import { Route as InstagramStoriesRouteImport } from './routes/instagram.stories'
import { Route as InstagramPublicacoesRouteImport } from './routes/instagram.publicacoes'
import { Route as InstagramMensagensRouteImport } from './routes/instagram.mensagens'
import { Route as InstagramDiagnosticoRouteImport } from './routes/instagram.diagnostico'
import { Route as InstagramDashboardRouteImport } from './routes/instagram.dashboard'
import { Route as InstagramConfiguracoesRouteImport } from './routes/instagram.configuracoes'
import { Route as InstagramComentariosRouteImport } from './routes/instagram.comentarios'
import { Route as InstagramAutomacoesRouteImport } from './routes/instagram.automacoes'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as ConfiguracoesSessoesWhatsappRouteImport } from './routes/configuracoes.sessoes-whatsapp'
import { Route as ConfiguracoesEnviosWhatsappRouteImport } from './routes/configuracoes.envios-whatsapp'
import { Route as TemplatesEditorIdRouteImport } from './routes/templates.editor.$id'
import { Route as CanaisIdEditarRouteImport } from './routes/canais.$id.editar'
import { Route as ApiPublicImgProxyRouteImport } from './routes/api/public/img-proxy'
import { Route as ApiMlProbeRouteImport } from './routes/api/ml/probe'
import { Route as ApiMlCallbackRouteImport } from './routes/api/ml/callback'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicWhatsappDiagnosticRouteImport } from './routes/api/public/whatsapp/diagnostic'
import { Route as ApiPublicWhatsappConnectRouteImport } from './routes/api/public/whatsapp/connect'
import { Route as ApiPublicWebhooksInstagramRouteImport } from './routes/api/public/webhooks/instagram'
import { Route as ApiPublicMetaWebhookRouteImport } from './routes/api/public/meta/webhook'
import { Route as ApiPublicInstagramCallbackRouteImport } from './routes/api/public/instagram/callback'
import { Route as ApiPublicHooksShopeeReportsSyncRouteImport } from './routes/api/public/hooks/shopee-reports-sync'
import { Route as ApiPublicHooksProductsValidateRouteImport } from './routes/api/public/hooks/products-validate'
import { Route as ApiPublicHooksPriceBackfillRouteImport } from './routes/api/public/hooks/price-backfill'
import { Route as ApiPublicHooksInstagramTickRouteImport } from './routes/api/public/hooks/instagram-tick'
import { Route as ApiPublicHooksEvolutionHealthcheckRouteImport } from './routes/api/public/hooks/evolution-healthcheck'
import { Route as ApiPublicHooksDebugShopeeProductRouteImport } from './routes/api/public/hooks/debug-shopee-product'
import { Route as ApiPublicHooksAutomationTickRouteImport } from './routes/api/public/hooks/automation-tick'
import { Route as ApiPublicInstabotREventIdRouteImport } from './routes/api/public/instabot/r.$eventId'
import { Route as ApiPublicChannelsWhatsappSessionStatusRouteImport } from './routes/api/public/channels/whatsapp/session-status'
import { Route as ApiPublicChannelsWhatsappConnectRouteImport } from './routes/api/public/channels/whatsapp/connect'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const FalhasRoute = FalhasRouteImport.update({
  id: '/falhas',
  path: '/falhas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigAfiliadosRoute = ConfigAfiliadosRouteImport.update({
  id: '/config-afiliados',
  path: '/config-afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramTemplatesRoute = InstagramTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => InstagramRoute,
} as any)
const InstagramStoriesRoute = InstagramStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => InstagramRoute,
} as any)
const InstagramPublicacoesRoute = InstagramPublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => InstagramRoute,
} as any)
const InstagramMensagensRoute = InstagramMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => InstagramRoute,
} as any)
const InstagramDiagnosticoRoute = InstagramDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => InstagramRoute,
} as any)
const InstagramDashboardRoute = InstagramDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstagramRoute,
} as any)
const InstagramConfiguracoesRoute = InstagramConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => InstagramRoute,
} as any)
const InstagramComentariosRoute = InstagramComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => InstagramRoute,
} as any)
const InstagramAutomacoesRoute = InstagramAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => InstagramRoute,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesSessoesWhatsappRoute =
  ConfiguracoesSessoesWhatsappRouteImport.update({
    id: '/configuracoes/sessoes-whatsapp',
    path: '/configuracoes/sessoes-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesEnviosWhatsappRoute =
  ConfiguracoesEnviosWhatsappRouteImport.update({
    id: '/configuracoes/envios-whatsapp',
    path: '/configuracoes/envios-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplatesEditorIdRoute = TemplatesEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => TemplatesRoute,
} as any)
const CanaisIdEditarRoute = CanaisIdEditarRouteImport.update({
  id: '/canais/$id/editar',
  path: '/canais/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgProxyRoute = ApiPublicImgProxyRouteImport.update({
  id: '/api/public/img-proxy',
  path: '/api/public/img-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlProbeRoute = ApiMlProbeRouteImport.update({
  id: '/api/ml/probe',
  path: '/api/ml/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlCallbackRoute = ApiMlCallbackRouteImport.update({
  id: '/api/ml/callback',
  path: '/api/ml/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappDiagnosticRoute =
  ApiPublicWhatsappDiagnosticRouteImport.update({
    id: '/api/public/whatsapp/diagnostic',
    path: '/api/public/whatsapp/diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappConnectRoute =
  ApiPublicWhatsappConnectRouteImport.update({
    id: '/api/public/whatsapp/connect',
    path: '/api/public/whatsapp/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksInstagramRoute =
  ApiPublicWebhooksInstagramRouteImport.update({
    id: '/api/public/webhooks/instagram',
    path: '/api/public/webhooks/instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaWebhookRoute = ApiPublicMetaWebhookRouteImport.update({
  id: '/api/public/meta/webhook',
  path: '/api/public/meta/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramCallbackRoute =
  ApiPublicInstagramCallbackRouteImport.update({
    id: '/api/public/instagram/callback',
    path: '/api/public/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShopeeReportsSyncRoute =
  ApiPublicHooksShopeeReportsSyncRouteImport.update({
    id: '/api/public/hooks/shopee-reports-sync',
    path: '/api/public/hooks/shopee-reports-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProductsValidateRoute =
  ApiPublicHooksProductsValidateRouteImport.update({
    id: '/api/public/hooks/products-validate',
    path: '/api/public/hooks/products-validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPriceBackfillRoute =
  ApiPublicHooksPriceBackfillRouteImport.update({
    id: '/api/public/hooks/price-backfill',
    path: '/api/public/hooks/price-backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInstagramTickRoute =
  ApiPublicHooksInstagramTickRouteImport.update({
    id: '/api/public/hooks/instagram-tick',
    path: '/api/public/hooks/instagram-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEvolutionHealthcheckRoute =
  ApiPublicHooksEvolutionHealthcheckRouteImport.update({
    id: '/api/public/hooks/evolution-healthcheck',
    path: '/api/public/hooks/evolution-healthcheck',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDebugShopeeProductRoute =
  ApiPublicHooksDebugShopeeProductRouteImport.update({
    id: '/api/public/hooks/debug-shopee-product',
    path: '/api/public/hooks/debug-shopee-product',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationTickRoute =
  ApiPublicHooksAutomationTickRouteImport.update({
    id: '/api/public/hooks/automation-tick',
    path: '/api/public/hooks/automation-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstabotREventIdRoute =
  ApiPublicInstabotREventIdRouteImport.update({
    id: '/api/public/instabot/r/$eventId',
    path: '/api/public/instabot/r/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChannelsWhatsappSessionStatusRoute =
  ApiPublicChannelsWhatsappSessionStatusRouteImport.update({
    id: '/api/public/channels/whatsapp/session-status',
    path: '/api/public/channels/whatsapp/session-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChannelsWhatsappConnectRoute =
  ApiPublicChannelsWhatsappConnectRouteImport.update({
    id: '/api/public/channels/whatsapp/connect',
    path: '/api/public/channels/whatsapp/connect',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/config-afiliados': typeof ConfigAfiliadosRoute
  '/falhas': typeof FalhasRoute
  '/instagram': typeof InstagramRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/configuracoes/envios-whatsapp': typeof ConfiguracoesEnviosWhatsappRoute
  '/configuracoes/sessoes-whatsapp': typeof ConfiguracoesSessoesWhatsappRoute
  '/g/$slug': typeof GSlugRoute
  '/instagram/automacoes': typeof InstagramAutomacoesRoute
  '/instagram/comentarios': typeof InstagramComentariosRoute
  '/instagram/configuracoes': typeof InstagramConfiguracoesRoute
  '/instagram/dashboard': typeof InstagramDashboardRoute
  '/instagram/diagnostico': typeof InstagramDiagnosticoRoute
  '/instagram/mensagens': typeof InstagramMensagensRoute
  '/instagram/publicacoes': typeof InstagramPublicacoesRoute
  '/instagram/stories': typeof InstagramStoriesRoute
  '/instagram/templates': typeof InstagramTemplatesRoute
  '/api/ml/callback': typeof ApiMlCallbackRoute
  '/api/ml/probe': typeof ApiMlProbeRoute
  '/api/public/img-proxy': typeof ApiPublicImgProxyRoute
  '/canais/$id/editar': typeof CanaisIdEditarRoute
  '/templates/editor/$id': typeof TemplatesEditorIdRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/hooks/debug-shopee-product': typeof ApiPublicHooksDebugShopeeProductRoute
  '/api/public/hooks/evolution-healthcheck': typeof ApiPublicHooksEvolutionHealthcheckRoute
  '/api/public/hooks/instagram-tick': typeof ApiPublicHooksInstagramTickRoute
  '/api/public/hooks/price-backfill': typeof ApiPublicHooksPriceBackfillRoute
  '/api/public/hooks/products-validate': typeof ApiPublicHooksProductsValidateRoute
  '/api/public/hooks/shopee-reports-sync': typeof ApiPublicHooksShopeeReportsSyncRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
  '/api/public/whatsapp/connect': typeof ApiPublicWhatsappConnectRoute
  '/api/public/whatsapp/diagnostic': typeof ApiPublicWhatsappDiagnosticRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/channels/whatsapp/connect': typeof ApiPublicChannelsWhatsappConnectRoute
  '/api/public/channels/whatsapp/session-status': typeof ApiPublicChannelsWhatsappSessionStatusRoute
  '/api/public/instabot/r/$eventId': typeof ApiPublicInstabotREventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/config-afiliados': typeof ConfigAfiliadosRoute
  '/falhas': typeof FalhasRoute
  '/instagram': typeof InstagramRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/configuracoes/envios-whatsapp': typeof ConfiguracoesEnviosWhatsappRoute
  '/configuracoes/sessoes-whatsapp': typeof ConfiguracoesSessoesWhatsappRoute
  '/g/$slug': typeof GSlugRoute
  '/instagram/automacoes': typeof InstagramAutomacoesRoute
  '/instagram/comentarios': typeof InstagramComentariosRoute
  '/instagram/configuracoes': typeof InstagramConfiguracoesRoute
  '/instagram/dashboard': typeof InstagramDashboardRoute
  '/instagram/diagnostico': typeof InstagramDiagnosticoRoute
  '/instagram/mensagens': typeof InstagramMensagensRoute
  '/instagram/publicacoes': typeof InstagramPublicacoesRoute
  '/instagram/stories': typeof InstagramStoriesRoute
  '/instagram/templates': typeof InstagramTemplatesRoute
  '/api/ml/callback': typeof ApiMlCallbackRoute
  '/api/ml/probe': typeof ApiMlProbeRoute
  '/api/public/img-proxy': typeof ApiPublicImgProxyRoute
  '/canais/$id/editar': typeof CanaisIdEditarRoute
  '/templates/editor/$id': typeof TemplatesEditorIdRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/hooks/debug-shopee-product': typeof ApiPublicHooksDebugShopeeProductRoute
  '/api/public/hooks/evolution-healthcheck': typeof ApiPublicHooksEvolutionHealthcheckRoute
  '/api/public/hooks/instagram-tick': typeof ApiPublicHooksInstagramTickRoute
  '/api/public/hooks/price-backfill': typeof ApiPublicHooksPriceBackfillRoute
  '/api/public/hooks/products-validate': typeof ApiPublicHooksProductsValidateRoute
  '/api/public/hooks/shopee-reports-sync': typeof ApiPublicHooksShopeeReportsSyncRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
  '/api/public/whatsapp/connect': typeof ApiPublicWhatsappConnectRoute
  '/api/public/whatsapp/diagnostic': typeof ApiPublicWhatsappDiagnosticRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/channels/whatsapp/connect': typeof ApiPublicChannelsWhatsappConnectRoute
  '/api/public/channels/whatsapp/session-status': typeof ApiPublicChannelsWhatsappSessionStatusRoute
  '/api/public/instabot/r/$eventId': typeof ApiPublicInstabotREventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/config-afiliados': typeof ConfigAfiliadosRoute
  '/falhas': typeof FalhasRoute
  '/instagram': typeof InstagramRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/configuracoes/envios-whatsapp': typeof ConfiguracoesEnviosWhatsappRoute
  '/configuracoes/sessoes-whatsapp': typeof ConfiguracoesSessoesWhatsappRoute
  '/g/$slug': typeof GSlugRoute
  '/instagram/automacoes': typeof InstagramAutomacoesRoute
  '/instagram/comentarios': typeof InstagramComentariosRoute
  '/instagram/configuracoes': typeof InstagramConfiguracoesRoute
  '/instagram/dashboard': typeof InstagramDashboardRoute
  '/instagram/diagnostico': typeof InstagramDiagnosticoRoute
  '/instagram/mensagens': typeof InstagramMensagensRoute
  '/instagram/publicacoes': typeof InstagramPublicacoesRoute
  '/instagram/stories': typeof InstagramStoriesRoute
  '/instagram/templates': typeof InstagramTemplatesRoute
  '/api/ml/callback': typeof ApiMlCallbackRoute
  '/api/ml/probe': typeof ApiMlProbeRoute
  '/api/public/img-proxy': typeof ApiPublicImgProxyRoute
  '/canais/$id/editar': typeof CanaisIdEditarRoute
  '/templates/editor/$id': typeof TemplatesEditorIdRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/hooks/debug-shopee-product': typeof ApiPublicHooksDebugShopeeProductRoute
  '/api/public/hooks/evolution-healthcheck': typeof ApiPublicHooksEvolutionHealthcheckRoute
  '/api/public/hooks/instagram-tick': typeof ApiPublicHooksInstagramTickRoute
  '/api/public/hooks/price-backfill': typeof ApiPublicHooksPriceBackfillRoute
  '/api/public/hooks/products-validate': typeof ApiPublicHooksProductsValidateRoute
  '/api/public/hooks/shopee-reports-sync': typeof ApiPublicHooksShopeeReportsSyncRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/meta/webhook': typeof ApiPublicMetaWebhookRoute
  '/api/public/webhooks/instagram': typeof ApiPublicWebhooksInstagramRoute
  '/api/public/whatsapp/connect': typeof ApiPublicWhatsappConnectRoute
  '/api/public/whatsapp/diagnostic': typeof ApiPublicWhatsappDiagnosticRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/channels/whatsapp/connect': typeof ApiPublicChannelsWhatsappConnectRoute
  '/api/public/channels/whatsapp/session-status': typeof ApiPublicChannelsWhatsappSessionStatusRoute
  '/api/public/instabot/r/$eventId': typeof ApiPublicInstabotREventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/config-afiliados'
    | '/falhas'
    | '/instagram'
    | '/relatorios'
    | '/templates'
    | '/configuracoes/envios-whatsapp'
    | '/configuracoes/sessoes-whatsapp'
    | '/g/$slug'
    | '/instagram/automacoes'
    | '/instagram/comentarios'
    | '/instagram/configuracoes'
    | '/instagram/dashboard'
    | '/instagram/diagnostico'
    | '/instagram/mensagens'
    | '/instagram/publicacoes'
    | '/instagram/stories'
    | '/instagram/templates'
    | '/api/ml/callback'
    | '/api/ml/probe'
    | '/api/public/img-proxy'
    | '/canais/$id/editar'
    | '/templates/editor/$id'
    | '/api/public/hooks/automation-tick'
    | '/api/public/hooks/debug-shopee-product'
    | '/api/public/hooks/evolution-healthcheck'
    | '/api/public/hooks/instagram-tick'
    | '/api/public/hooks/price-backfill'
    | '/api/public/hooks/products-validate'
    | '/api/public/hooks/shopee-reports-sync'
    | '/api/public/instagram/callback'
    | '/api/public/meta/webhook'
    | '/api/public/webhooks/instagram'
    | '/api/public/whatsapp/connect'
    | '/api/public/whatsapp/diagnostic'
    | '/api/public/whatsapp/webhook'
    | '/api/public/channels/whatsapp/connect'
    | '/api/public/channels/whatsapp/session-status'
    | '/api/public/instabot/r/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/config-afiliados'
    | '/falhas'
    | '/instagram'
    | '/relatorios'
    | '/templates'
    | '/configuracoes/envios-whatsapp'
    | '/configuracoes/sessoes-whatsapp'
    | '/g/$slug'
    | '/instagram/automacoes'
    | '/instagram/comentarios'
    | '/instagram/configuracoes'
    | '/instagram/dashboard'
    | '/instagram/diagnostico'
    | '/instagram/mensagens'
    | '/instagram/publicacoes'
    | '/instagram/stories'
    | '/instagram/templates'
    | '/api/ml/callback'
    | '/api/ml/probe'
    | '/api/public/img-proxy'
    | '/canais/$id/editar'
    | '/templates/editor/$id'
    | '/api/public/hooks/automation-tick'
    | '/api/public/hooks/debug-shopee-product'
    | '/api/public/hooks/evolution-healthcheck'
    | '/api/public/hooks/instagram-tick'
    | '/api/public/hooks/price-backfill'
    | '/api/public/hooks/products-validate'
    | '/api/public/hooks/shopee-reports-sync'
    | '/api/public/instagram/callback'
    | '/api/public/meta/webhook'
    | '/api/public/webhooks/instagram'
    | '/api/public/whatsapp/connect'
    | '/api/public/whatsapp/diagnostic'
    | '/api/public/whatsapp/webhook'
    | '/api/public/channels/whatsapp/connect'
    | '/api/public/channels/whatsapp/session-status'
    | '/api/public/instabot/r/$eventId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/config-afiliados'
    | '/falhas'
    | '/instagram'
    | '/relatorios'
    | '/templates'
    | '/configuracoes/envios-whatsapp'
    | '/configuracoes/sessoes-whatsapp'
    | '/g/$slug'
    | '/instagram/automacoes'
    | '/instagram/comentarios'
    | '/instagram/configuracoes'
    | '/instagram/dashboard'
    | '/instagram/diagnostico'
    | '/instagram/mensagens'
    | '/instagram/publicacoes'
    | '/instagram/stories'
    | '/instagram/templates'
    | '/api/ml/callback'
    | '/api/ml/probe'
    | '/api/public/img-proxy'
    | '/canais/$id/editar'
    | '/templates/editor/$id'
    | '/api/public/hooks/automation-tick'
    | '/api/public/hooks/debug-shopee-product'
    | '/api/public/hooks/evolution-healthcheck'
    | '/api/public/hooks/instagram-tick'
    | '/api/public/hooks/price-backfill'
    | '/api/public/hooks/products-validate'
    | '/api/public/hooks/shopee-reports-sync'
    | '/api/public/instagram/callback'
    | '/api/public/meta/webhook'
    | '/api/public/webhooks/instagram'
    | '/api/public/whatsapp/connect'
    | '/api/public/whatsapp/diagnostic'
    | '/api/public/whatsapp/webhook'
    | '/api/public/channels/whatsapp/connect'
    | '/api/public/channels/whatsapp/session-status'
    | '/api/public/instabot/r/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfigAfiliadosRoute: typeof ConfigAfiliadosRoute
  FalhasRoute: typeof FalhasRoute
  InstagramRoute: typeof InstagramRouteWithChildren
  RelatoriosRoute: typeof RelatoriosRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  ConfiguracoesEnviosWhatsappRoute: typeof ConfiguracoesEnviosWhatsappRoute
  ConfiguracoesSessoesWhatsappRoute: typeof ConfiguracoesSessoesWhatsappRoute
  GSlugRoute: typeof GSlugRoute
  ApiMlCallbackRoute: typeof ApiMlCallbackRoute
  ApiMlProbeRoute: typeof ApiMlProbeRoute
  ApiPublicImgProxyRoute: typeof ApiPublicImgProxyRoute
  CanaisIdEditarRoute: typeof CanaisIdEditarRoute
  ApiPublicHooksAutomationTickRoute: typeof ApiPublicHooksAutomationTickRoute
  ApiPublicHooksDebugShopeeProductRoute: typeof ApiPublicHooksDebugShopeeProductRoute
  ApiPublicHooksEvolutionHealthcheckRoute: typeof ApiPublicHooksEvolutionHealthcheckRoute
  ApiPublicHooksInstagramTickRoute: typeof ApiPublicHooksInstagramTickRoute
  ApiPublicHooksPriceBackfillRoute: typeof ApiPublicHooksPriceBackfillRoute
  ApiPublicHooksProductsValidateRoute: typeof ApiPublicHooksProductsValidateRoute
  ApiPublicHooksShopeeReportsSyncRoute: typeof ApiPublicHooksShopeeReportsSyncRoute
  ApiPublicInstagramCallbackRoute: typeof ApiPublicInstagramCallbackRoute
  ApiPublicMetaWebhookRoute: typeof ApiPublicMetaWebhookRoute
  ApiPublicWebhooksInstagramRoute: typeof ApiPublicWebhooksInstagramRoute
  ApiPublicWhatsappConnectRoute: typeof ApiPublicWhatsappConnectRoute
  ApiPublicWhatsappDiagnosticRoute: typeof ApiPublicWhatsappDiagnosticRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicChannelsWhatsappConnectRoute: typeof ApiPublicChannelsWhatsappConnectRoute
  ApiPublicChannelsWhatsappSessionStatusRoute: typeof ApiPublicChannelsWhatsappSessionStatusRoute
  ApiPublicInstabotREventIdRoute: typeof ApiPublicInstabotREventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/falhas': {
      id: '/falhas'
      path: '/falhas'
      fullPath: '/falhas'
      preLoaderRoute: typeof FalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-afiliados': {
      id: '/config-afiliados'
      path: '/config-afiliados'
      fullPath: '/config-afiliados'
      preLoaderRoute: typeof ConfigAfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram/templates': {
      id: '/instagram/templates'
      path: '/templates'
      fullPath: '/instagram/templates'
      preLoaderRoute: typeof InstagramTemplatesRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/instagram/stories': {
      id: '/instagram/stories'
      path: '/stories'
      fullPath: '/instagram/stories'
      preLoaderRoute: typeof InstagramStoriesRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/instagram/publicacoes': {
      id: '/instagram/publicacoes'
      path: '/publicacoes'
      fullPath: '/instagram/publicacoes'
      preLoaderRoute: typeof InstagramPublicacoesRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/instagram/mensagens': {
      id: '/instagram/mensagens'
      path: '/mensagens'
      fullPath: '/instagram/mensagens'
      preLoaderRoute: typeof InstagramMensagensRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/instagram/diagnostico': {
      id: '/instagram/diagnostico'
      path: '/diagnostico'
      fullPath: '/instagram/diagnostico'
      preLoaderRoute: typeof InstagramDiagnosticoRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/instagram/dashboard': {
      id: '/instagram/dashboard'
      path: '/dashboard'
      fullPath: '/instagram/dashboard'
      preLoaderRoute: typeof InstagramDashboardRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/instagram/configuracoes': {
      id: '/instagram/configuracoes'
      path: '/configuracoes'
      fullPath: '/instagram/configuracoes'
      preLoaderRoute: typeof InstagramConfiguracoesRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/instagram/comentarios': {
      id: '/instagram/comentarios'
      path: '/comentarios'
      fullPath: '/instagram/comentarios'
      preLoaderRoute: typeof InstagramComentariosRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/instagram/automacoes': {
      id: '/instagram/automacoes'
      path: '/automacoes'
      fullPath: '/instagram/automacoes'
      preLoaderRoute: typeof InstagramAutomacoesRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/sessoes-whatsapp': {
      id: '/configuracoes/sessoes-whatsapp'
      path: '/configuracoes/sessoes-whatsapp'
      fullPath: '/configuracoes/sessoes-whatsapp'
      preLoaderRoute: typeof ConfiguracoesSessoesWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/envios-whatsapp': {
      id: '/configuracoes/envios-whatsapp'
      path: '/configuracoes/envios-whatsapp'
      fullPath: '/configuracoes/envios-whatsapp'
      preLoaderRoute: typeof ConfiguracoesEnviosWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/editor/$id': {
      id: '/templates/editor/$id'
      path: '/editor/$id'
      fullPath: '/templates/editor/$id'
      preLoaderRoute: typeof TemplatesEditorIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/canais/$id/editar': {
      id: '/canais/$id/editar'
      path: '/canais/$id/editar'
      fullPath: '/canais/$id/editar'
      preLoaderRoute: typeof CanaisIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img-proxy': {
      id: '/api/public/img-proxy'
      path: '/api/public/img-proxy'
      fullPath: '/api/public/img-proxy'
      preLoaderRoute: typeof ApiPublicImgProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/probe': {
      id: '/api/ml/probe'
      path: '/api/ml/probe'
      fullPath: '/api/ml/probe'
      preLoaderRoute: typeof ApiMlProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/callback': {
      id: '/api/ml/callback'
      path: '/api/ml/callback'
      fullPath: '/api/ml/callback'
      preLoaderRoute: typeof ApiMlCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/diagnostic': {
      id: '/api/public/whatsapp/diagnostic'
      path: '/api/public/whatsapp/diagnostic'
      fullPath: '/api/public/whatsapp/diagnostic'
      preLoaderRoute: typeof ApiPublicWhatsappDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/connect': {
      id: '/api/public/whatsapp/connect'
      path: '/api/public/whatsapp/connect'
      fullPath: '/api/public/whatsapp/connect'
      preLoaderRoute: typeof ApiPublicWhatsappConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/instagram': {
      id: '/api/public/webhooks/instagram'
      path: '/api/public/webhooks/instagram'
      fullPath: '/api/public/webhooks/instagram'
      preLoaderRoute: typeof ApiPublicWebhooksInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/webhook': {
      id: '/api/public/meta/webhook'
      path: '/api/public/meta/webhook'
      fullPath: '/api/public/meta/webhook'
      preLoaderRoute: typeof ApiPublicMetaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram/callback': {
      id: '/api/public/instagram/callback'
      path: '/api/public/instagram/callback'
      fullPath: '/api/public/instagram/callback'
      preLoaderRoute: typeof ApiPublicInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shopee-reports-sync': {
      id: '/api/public/hooks/shopee-reports-sync'
      path: '/api/public/hooks/shopee-reports-sync'
      fullPath: '/api/public/hooks/shopee-reports-sync'
      preLoaderRoute: typeof ApiPublicHooksShopeeReportsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/products-validate': {
      id: '/api/public/hooks/products-validate'
      path: '/api/public/hooks/products-validate'
      fullPath: '/api/public/hooks/products-validate'
      preLoaderRoute: typeof ApiPublicHooksProductsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/price-backfill': {
      id: '/api/public/hooks/price-backfill'
      path: '/api/public/hooks/price-backfill'
      fullPath: '/api/public/hooks/price-backfill'
      preLoaderRoute: typeof ApiPublicHooksPriceBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/instagram-tick': {
      id: '/api/public/hooks/instagram-tick'
      path: '/api/public/hooks/instagram-tick'
      fullPath: '/api/public/hooks/instagram-tick'
      preLoaderRoute: typeof ApiPublicHooksInstagramTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/evolution-healthcheck': {
      id: '/api/public/hooks/evolution-healthcheck'
      path: '/api/public/hooks/evolution-healthcheck'
      fullPath: '/api/public/hooks/evolution-healthcheck'
      preLoaderRoute: typeof ApiPublicHooksEvolutionHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/debug-shopee-product': {
      id: '/api/public/hooks/debug-shopee-product'
      path: '/api/public/hooks/debug-shopee-product'
      fullPath: '/api/public/hooks/debug-shopee-product'
      preLoaderRoute: typeof ApiPublicHooksDebugShopeeProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-tick': {
      id: '/api/public/hooks/automation-tick'
      path: '/api/public/hooks/automation-tick'
      fullPath: '/api/public/hooks/automation-tick'
      preLoaderRoute: typeof ApiPublicHooksAutomationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instabot/r/$eventId': {
      id: '/api/public/instabot/r/$eventId'
      path: '/api/public/instabot/r/$eventId'
      fullPath: '/api/public/instabot/r/$eventId'
      preLoaderRoute: typeof ApiPublicInstabotREventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/channels/whatsapp/session-status': {
      id: '/api/public/channels/whatsapp/session-status'
      path: '/api/public/channels/whatsapp/session-status'
      fullPath: '/api/public/channels/whatsapp/session-status'
      preLoaderRoute: typeof ApiPublicChannelsWhatsappSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/channels/whatsapp/connect': {
      id: '/api/public/channels/whatsapp/connect'
      path: '/api/public/channels/whatsapp/connect'
      fullPath: '/api/public/channels/whatsapp/connect'
      preLoaderRoute: typeof ApiPublicChannelsWhatsappConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InstagramRouteChildren {
  InstagramAutomacoesRoute: typeof InstagramAutomacoesRoute
  InstagramComentariosRoute: typeof InstagramComentariosRoute
  InstagramConfiguracoesRoute: typeof InstagramConfiguracoesRoute
  InstagramDashboardRoute: typeof InstagramDashboardRoute
  InstagramDiagnosticoRoute: typeof InstagramDiagnosticoRoute
  InstagramMensagensRoute: typeof InstagramMensagensRoute
  InstagramPublicacoesRoute: typeof InstagramPublicacoesRoute
  InstagramStoriesRoute: typeof InstagramStoriesRoute
  InstagramTemplatesRoute: typeof InstagramTemplatesRoute
}

const InstagramRouteChildren: InstagramRouteChildren = {
  InstagramAutomacoesRoute: InstagramAutomacoesRoute,
  InstagramComentariosRoute: InstagramComentariosRoute,
  InstagramConfiguracoesRoute: InstagramConfiguracoesRoute,
  InstagramDashboardRoute: InstagramDashboardRoute,
  InstagramDiagnosticoRoute: InstagramDiagnosticoRoute,
  InstagramMensagensRoute: InstagramMensagensRoute,
  InstagramPublicacoesRoute: InstagramPublicacoesRoute,
  InstagramStoriesRoute: InstagramStoriesRoute,
  InstagramTemplatesRoute: InstagramTemplatesRoute,
}

const InstagramRouteWithChildren = InstagramRoute._addFileChildren(
  InstagramRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesEditorIdRoute: typeof TemplatesEditorIdRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesEditorIdRoute: TemplatesEditorIdRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfigAfiliadosRoute: ConfigAfiliadosRoute,
  FalhasRoute: FalhasRoute,
  InstagramRoute: InstagramRouteWithChildren,
  RelatoriosRoute: RelatoriosRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  ConfiguracoesEnviosWhatsappRoute: ConfiguracoesEnviosWhatsappRoute,
  ConfiguracoesSessoesWhatsappRoute: ConfiguracoesSessoesWhatsappRoute,
  GSlugRoute: GSlugRoute,
  ApiMlCallbackRoute: ApiMlCallbackRoute,
  ApiMlProbeRoute: ApiMlProbeRoute,
  ApiPublicImgProxyRoute: ApiPublicImgProxyRoute,
  CanaisIdEditarRoute: CanaisIdEditarRoute,
  ApiPublicHooksAutomationTickRoute: ApiPublicHooksAutomationTickRoute,
  ApiPublicHooksDebugShopeeProductRoute: ApiPublicHooksDebugShopeeProductRoute,
  ApiPublicHooksEvolutionHealthcheckRoute:
    ApiPublicHooksEvolutionHealthcheckRoute,
  ApiPublicHooksInstagramTickRoute: ApiPublicHooksInstagramTickRoute,
  ApiPublicHooksPriceBackfillRoute: ApiPublicHooksPriceBackfillRoute,
  ApiPublicHooksProductsValidateRoute: ApiPublicHooksProductsValidateRoute,
  ApiPublicHooksShopeeReportsSyncRoute: ApiPublicHooksShopeeReportsSyncRoute,
  ApiPublicInstagramCallbackRoute: ApiPublicInstagramCallbackRoute,
  ApiPublicMetaWebhookRoute: ApiPublicMetaWebhookRoute,
  ApiPublicWebhooksInstagramRoute: ApiPublicWebhooksInstagramRoute,
  ApiPublicWhatsappConnectRoute: ApiPublicWhatsappConnectRoute,
  ApiPublicWhatsappDiagnosticRoute: ApiPublicWhatsappDiagnosticRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicChannelsWhatsappConnectRoute: ApiPublicChannelsWhatsappConnectRoute,
  ApiPublicChannelsWhatsappSessionStatusRoute:
    ApiPublicChannelsWhatsappSessionStatusRoute,
  ApiPublicInstabotREventIdRoute: ApiPublicInstabotREventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
