/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ConfigAfiliadosRouteImport } from './routes/config-afiliados'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesSessoesWhatsappRouteImport } from './routes/configuracoes.sessoes-whatsapp'
import { Route as CanaisIdEditarRouteImport } from './routes/canais.$id.editar'
import { Route as ApiMlProbeRouteImport } from './routes/api/ml/probe'
import { Route as ApiMlCallbackRouteImport } from './routes/api/ml/callback'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicWhatsappDiagnosticRouteImport } from './routes/api/public/whatsapp/diagnostic'
import { Route as ApiPublicWhatsappConnectRouteImport } from './routes/api/public/whatsapp/connect'
import { Route as ApiPublicChannelsWhatsappSessionStatusRouteImport } from './routes/api/public/channels/whatsapp/session-status'
import { Route as ApiPublicChannelsWhatsappConnectRouteImport } from './routes/api/public/channels/whatsapp/connect'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigAfiliadosRoute = ConfigAfiliadosRouteImport.update({
  id: '/config-afiliados',
  path: '/config-afiliados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesSessoesWhatsappRoute =
  ConfiguracoesSessoesWhatsappRouteImport.update({
    id: '/configuracoes/sessoes-whatsapp',
    path: '/configuracoes/sessoes-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const CanaisIdEditarRoute = CanaisIdEditarRouteImport.update({
  id: '/canais/$id/editar',
  path: '/canais/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlProbeRoute = ApiMlProbeRouteImport.update({
  id: '/api/ml/probe',
  path: '/api/ml/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMlCallbackRoute = ApiMlCallbackRouteImport.update({
  id: '/api/ml/callback',
  path: '/api/ml/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappDiagnosticRoute =
  ApiPublicWhatsappDiagnosticRouteImport.update({
    id: '/api/public/whatsapp/diagnostic',
    path: '/api/public/whatsapp/diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappConnectRoute =
  ApiPublicWhatsappConnectRouteImport.update({
    id: '/api/public/whatsapp/connect',
    path: '/api/public/whatsapp/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChannelsWhatsappSessionStatusRoute =
  ApiPublicChannelsWhatsappSessionStatusRouteImport.update({
    id: '/api/public/channels/whatsapp/session-status',
    path: '/api/public/channels/whatsapp/session-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChannelsWhatsappConnectRoute =
  ApiPublicChannelsWhatsappConnectRouteImport.update({
    id: '/api/public/channels/whatsapp/connect',
    path: '/api/public/channels/whatsapp/connect',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/config-afiliados': typeof ConfigAfiliadosRoute
  '/relatorios': typeof RelatoriosRoute
  '/configuracoes/sessoes-whatsapp': typeof ConfiguracoesSessoesWhatsappRoute
  '/api/ml/callback': typeof ApiMlCallbackRoute
  '/api/ml/probe': typeof ApiMlProbeRoute
  '/canais/$id/editar': typeof CanaisIdEditarRoute
  '/api/public/whatsapp/connect': typeof ApiPublicWhatsappConnectRoute
  '/api/public/whatsapp/diagnostic': typeof ApiPublicWhatsappDiagnosticRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/channels/whatsapp/connect': typeof ApiPublicChannelsWhatsappConnectRoute
  '/api/public/channels/whatsapp/session-status': typeof ApiPublicChannelsWhatsappSessionStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/config-afiliados': typeof ConfigAfiliadosRoute
  '/relatorios': typeof RelatoriosRoute
  '/configuracoes/sessoes-whatsapp': typeof ConfiguracoesSessoesWhatsappRoute
  '/api/ml/callback': typeof ApiMlCallbackRoute
  '/api/ml/probe': typeof ApiMlProbeRoute
  '/canais/$id/editar': typeof CanaisIdEditarRoute
  '/api/public/whatsapp/connect': typeof ApiPublicWhatsappConnectRoute
  '/api/public/whatsapp/diagnostic': typeof ApiPublicWhatsappDiagnosticRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/channels/whatsapp/connect': typeof ApiPublicChannelsWhatsappConnectRoute
  '/api/public/channels/whatsapp/session-status': typeof ApiPublicChannelsWhatsappSessionStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/config-afiliados': typeof ConfigAfiliadosRoute
  '/relatorios': typeof RelatoriosRoute
  '/configuracoes/sessoes-whatsapp': typeof ConfiguracoesSessoesWhatsappRoute
  '/api/ml/callback': typeof ApiMlCallbackRoute
  '/api/ml/probe': typeof ApiMlProbeRoute
  '/canais/$id/editar': typeof CanaisIdEditarRoute
  '/api/public/whatsapp/connect': typeof ApiPublicWhatsappConnectRoute
  '/api/public/whatsapp/diagnostic': typeof ApiPublicWhatsappDiagnosticRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/channels/whatsapp/connect': typeof ApiPublicChannelsWhatsappConnectRoute
  '/api/public/channels/whatsapp/session-status': typeof ApiPublicChannelsWhatsappSessionStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/config-afiliados'
    | '/relatorios'
    | '/configuracoes/sessoes-whatsapp'
    | '/api/ml/callback'
    | '/api/ml/probe'
    | '/canais/$id/editar'
    | '/api/public/whatsapp/connect'
    | '/api/public/whatsapp/diagnostic'
    | '/api/public/whatsapp/webhook'
    | '/api/public/channels/whatsapp/connect'
    | '/api/public/channels/whatsapp/session-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/config-afiliados'
    | '/relatorios'
    | '/configuracoes/sessoes-whatsapp'
    | '/api/ml/callback'
    | '/api/ml/probe'
    | '/canais/$id/editar'
    | '/api/public/whatsapp/connect'
    | '/api/public/whatsapp/diagnostic'
    | '/api/public/whatsapp/webhook'
    | '/api/public/channels/whatsapp/connect'
    | '/api/public/channels/whatsapp/session-status'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/config-afiliados'
    | '/relatorios'
    | '/configuracoes/sessoes-whatsapp'
    | '/api/ml/callback'
    | '/api/ml/probe'
    | '/canais/$id/editar'
    | '/api/public/whatsapp/connect'
    | '/api/public/whatsapp/diagnostic'
    | '/api/public/whatsapp/webhook'
    | '/api/public/channels/whatsapp/connect'
    | '/api/public/channels/whatsapp/session-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConfigAfiliadosRoute: typeof ConfigAfiliadosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ConfiguracoesSessoesWhatsappRoute: typeof ConfiguracoesSessoesWhatsappRoute
  ApiMlCallbackRoute: typeof ApiMlCallbackRoute
  ApiMlProbeRoute: typeof ApiMlProbeRoute
  CanaisIdEditarRoute: typeof CanaisIdEditarRoute
  ApiPublicWhatsappConnectRoute: typeof ApiPublicWhatsappConnectRoute
  ApiPublicWhatsappDiagnosticRoute: typeof ApiPublicWhatsappDiagnosticRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicChannelsWhatsappConnectRoute: typeof ApiPublicChannelsWhatsappConnectRoute
  ApiPublicChannelsWhatsappSessionStatusRoute: typeof ApiPublicChannelsWhatsappSessionStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config-afiliados': {
      id: '/config-afiliados'
      path: '/config-afiliados'
      fullPath: '/config-afiliados'
      preLoaderRoute: typeof ConfigAfiliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/sessoes-whatsapp': {
      id: '/configuracoes/sessoes-whatsapp'
      path: '/configuracoes/sessoes-whatsapp'
      fullPath: '/configuracoes/sessoes-whatsapp'
      preLoaderRoute: typeof ConfiguracoesSessoesWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais/$id/editar': {
      id: '/canais/$id/editar'
      path: '/canais/$id/editar'
      fullPath: '/canais/$id/editar'
      preLoaderRoute: typeof CanaisIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/probe': {
      id: '/api/ml/probe'
      path: '/api/ml/probe'
      fullPath: '/api/ml/probe'
      preLoaderRoute: typeof ApiMlProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ml/callback': {
      id: '/api/ml/callback'
      path: '/api/ml/callback'
      fullPath: '/api/ml/callback'
      preLoaderRoute: typeof ApiMlCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/diagnostic': {
      id: '/api/public/whatsapp/diagnostic'
      path: '/api/public/whatsapp/diagnostic'
      fullPath: '/api/public/whatsapp/diagnostic'
      preLoaderRoute: typeof ApiPublicWhatsappDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/connect': {
      id: '/api/public/whatsapp/connect'
      path: '/api/public/whatsapp/connect'
      fullPath: '/api/public/whatsapp/connect'
      preLoaderRoute: typeof ApiPublicWhatsappConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/channels/whatsapp/session-status': {
      id: '/api/public/channels/whatsapp/session-status'
      path: '/api/public/channels/whatsapp/session-status'
      fullPath: '/api/public/channels/whatsapp/session-status'
      preLoaderRoute: typeof ApiPublicChannelsWhatsappSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/channels/whatsapp/connect': {
      id: '/api/public/channels/whatsapp/connect'
      path: '/api/public/channels/whatsapp/connect'
      fullPath: '/api/public/channels/whatsapp/connect'
      preLoaderRoute: typeof ApiPublicChannelsWhatsappConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConfigAfiliadosRoute: ConfigAfiliadosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ConfiguracoesSessoesWhatsappRoute: ConfiguracoesSessoesWhatsappRoute,
  ApiMlCallbackRoute: ApiMlCallbackRoute,
  ApiMlProbeRoute: ApiMlProbeRoute,
  CanaisIdEditarRoute: CanaisIdEditarRoute,
  ApiPublicWhatsappConnectRoute: ApiPublicWhatsappConnectRoute,
  ApiPublicWhatsappDiagnosticRoute: ApiPublicWhatsappDiagnosticRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicChannelsWhatsappConnectRoute: ApiPublicChannelsWhatsappConnectRoute,
  ApiPublicChannelsWhatsappSessionStatusRoute:
    ApiPublicChannelsWhatsappSessionStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
